# Railway-specific configuration
# This file is automatically detected by Railway

[build]
builder = "NIXPACKS"
buildCommand = "chmod +x railway-build.sh && ./railway-build.sh"

[deploy]
startCommand = "chmod +x railway-start.sh && ./railway-start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will auto-inject PORT and REDIS_URL
# You only need to manually set Alpaca credentials
